# Generated by Django 4.2.3 on 2023-07-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('unique_name',
                 models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('unique_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('unique_id',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='main.users', to_field='unique_id')),
                ('display_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('salt', models.CharField(max_length=50)),
            ],
        ),
    ]
