# Generated by Django 4.2.3 on 2023-07-09 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_id', models.CharField(max_length=15)),
                ('unique_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users', to_field='unique_id')),
            ],
        ),
    ]
