# Generated by Django 4.2.3 on 2023-07-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_snippets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippets',
            name='snippet_id',
            field=models.TextField(),
        ),
    ]
