# Generated by Django 4.2.3 on 2023-07-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_alter_snippets_snippet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippets',
            name='snippet_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='snippets',
            name='snippet_id',
            field=models.CharField(max_length=15),
        ),
    ]
