# Generated by Django 4.2.3 on 2023-07-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifySlugs',
            fields=[
                ('user_name',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='main.users')),
                ('verifycode', models.CharField(max_length=50)),
            ],
        ),
    ]
