# Generated by Django 4.2.3 on 2023-07-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyslugs',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.users', to_field='unique_id'),
        ),
    ]
