# Generated by Django 4.2.3 on 2023-07-08 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('oauth', '0002_alter_verifyslugs_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifyslugs',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
